import {
  Activity,
  BarChart3,
  BookOpen,
  BrainCircuit,
  Building2,
  FileText,
  Gauge,
  GraduationCap,
  LineChart,
  Medal,
  Radio,
  ShieldCheck,
  Trophy,
  Users,
} from "lucide-react";

export const rolePalettes = {
  student: {
    gradient: "from-[#79D99C] to-[#2B7886]",
    active: "bg-white text-[var(--role-primary)] shadow-[0_14px_32px_rgba(15,23,42,0.08)] ring-1 ring-[rgba(15,23,42,0.05)]",
    iconSoft: "bg-[var(--role-soft)] text-[var(--role-primary)]",
    ring: "ring-[var(--role-border)]",
    text: "text-[var(--role-text)]",
    vars: {
      "--role-bg": "#F4F5F4",
      "--role-surface": "#FFFFFF",
      "--role-primary": "#2B7886",
      "--role-primary-strong": "#245866",
      "--role-accent": "#79D99C",
      "--role-secondary": "#79D99C",
      "--role-info": "#EAF8F0",
      "--role-error": "#EF6B6B",
      "--role-soft": "#EAF8F0",
      "--role-hover": "#F8FAF8",
      "--role-text": "#101418",
      "--role-border": "#E8ECEA",
      "--role-glow": "rgba(43, 120, 134, 0.14)",
      "--role-radius": "28px",
      "--role-card-padding": "1.5rem",
      "--role-card-shadow": "0 18px 45px rgba(15, 23, 42, 0.08)",
      "--role-card-border": "rgba(15, 23, 42, 0.06)",
      "--role-pressed-shadow": "none",
      "--role-dark-soft": "rgba(43, 120, 134, 0.16)",
      "--role-dark-text": "#F8FAF8",
    },
  },
  instructor: {
    gradient: "from-[#79D99C] to-[#2B7886]",
    active: "bg-white text-[var(--role-primary)] shadow-[0_14px_32px_rgba(15,23,42,0.08)] ring-1 ring-[rgba(15,23,42,0.05)]",
    iconSoft: "bg-[var(--role-soft)] text-[var(--role-primary)]",
    ring: "ring-[var(--role-border)]",
    text: "text-[var(--role-text)]",
    vars: {
      "--role-bg": "#F4F5F4",
      "--role-surface": "#FFFFFF",
      "--role-primary": "#2B7886",
      "--role-primary-strong": "#245866",
      "--role-accent": "#79D99C",
      "--role-secondary": "#79D99C",
      "--role-info": "#EAF8F0",
      "--role-error": "#EF6B6B",
      "--role-soft": "#EAF8F0",
      "--role-hover": "#F8FAF8",
      "--role-text": "#101418",
      "--role-border": "#E8ECEA",
      "--role-glow": "rgba(43, 120, 134, 0.14)",
      "--role-radius": "28px",
      "--role-card-padding": "1.5rem",
      "--role-card-shadow": "0 18px 45px rgba(15, 23, 42, 0.08)",
      "--role-card-border": "rgba(15, 23, 42, 0.06)",
      "--role-pressed-shadow": "none",
      "--role-dark-soft": "rgba(43, 120, 134, 0.16)",
      "--role-dark-text": "#F8FAF8",
    },
  },
  admin: {
    gradient: "from-[#79D99C] to-[#2B7886]",
    active: "bg-white text-[var(--role-primary)] shadow-[0_14px_32px_rgba(15,23,42,0.08)] ring-1 ring-[rgba(15,23,42,0.05)]",
    iconSoft: "bg-[var(--role-soft)] text-[var(--role-primary)]",
    ring: "ring-[var(--role-border)]",
    text: "text-[var(--role-text)] dark:text-[var(--role-dark-text)]",
    vars: {
      "--role-bg": "#F4F5F4",
      "--role-surface": "#FFFFFF",
      "--role-primary": "#2B7886",
      "--role-primary-strong": "#245866",
      "--role-accent": "#79D99C",
      "--role-secondary": "#79D99C",
      "--role-info": "#EAF8F0",
      "--role-error": "#EF6B6B",
      "--role-soft": "#EAF8F0",
      "--role-hover": "#F8FAF8",
      "--role-text": "#101418",
      "--role-border": "#E8ECEA",
      "--role-glow": "rgba(43, 120, 134, 0.14)",
      "--role-radius": "28px",
      "--role-card-padding": "1.5rem",
      "--role-card-shadow": "0 18px 45px rgba(15, 23, 42, 0.08)",
      "--role-card-border": "rgba(15, 23, 42, 0.06)",
      "--role-pressed-shadow": "none",
      "--role-dark-soft": "rgba(37, 99, 235, 0.18)",
      "--role-dark-text": "#BFDBFE",
    },
  },
};

export const roleThemeScope = {
  student: "staff",
  instructor: "staff",
  admin: "staff",
};

export function getRoleThemeScope(role) {
  return roleThemeScope[role] ?? "staff";
}

export const roleMeta = {
  student: {
    label: "Student",
    name: "Student",
    workspace: "Student Space",
    palette: rolePalettes.student,
    tone: "emerald",
    focus: "Live streaks, badges, and fast classroom answers",
    icon: GraduationCap,
  },
  instructor: {
    label: "Instructor",
    name: "Instructor",
    workspace: "Instructor Workspace",
    palette: rolePalettes.instructor,
    tone: "slate",
    focus: "Question generation, session control, and live insight",
    icon: BookOpen,
  },
  admin: {
    label: "Administrator",
    name: "Administrator",
    workspace: "Institution Command Center",
    palette: rolePalettes.admin,
    tone: "orange",
    focus: "Institution health, risk, and reports",
    icon: ShieldCheck,
  },
};

export const navigation = {
  student: [
    { to: "/student", label: "Dashboard", icon: Gauge, end: true },
    { to: "/student/join", label: "Join Session", icon: Radio },
    { to: "/student/session", label: "Live Class", icon: BrainCircuit },
    { to: "/student/achievements", label: "Achievements", icon: Trophy },
    { to: "/student/leaderboard", label: "Leaderboard", icon: Medal },
    { to: "/student/progress", label: "Analytics", icon: BarChart3 },
  ],
  instructor: [
    { to: "/instructor", label: "Dashboard", icon: Gauge, end: true },
    { to: "/instructor/classes", label: "Classes", icon: Building2 },
    { to: "/instructor/content-studio", label: "Content Studio", icon: FileText },
    { to: "/instructor/sessions", label: "Sessions", icon: Radio },
    { to: "/instructor/live", label: "Live Class", icon: Activity },
    { to: "/instructor/analytics", label: "Analytics", icon: LineChart },
  ],
  admin: [
    { to: "/admin", label: "Dashboard", icon: Gauge, end: true },
    { to: "/admin/accounts", label: "Accounts", icon: Users },
    { to: "/admin/classes", label: "Classes", icon: Building2 },
    { to: "/admin/students", label: "Students", icon: Activity },
    {
      to: "/admin/insights/analytics",
      label: "Educational Intelligence",
      icon: BrainCircuit,
      matchPrefix: "/admin/insights",
      children: [
        { to: "/admin/insights/analytics", label: "Analytics", icon: BarChart3, end: true },
        { to: "/admin/insights/predictions", label: "Predictions", icon: FileText, end: true },
        { to: "/admin/insights/reports", label: "Reports", icon: LineChart, end: true },
      ],
    },
  ],
};
